<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Is Required</name>
   <tag></tag>
   <elementGuidId>173a5524-817b-41c4-8c73-9949e908310a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.el-switch-style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>446e7a84-bc63-4b12-b4a0-6522d2ffd275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-switch-style</value>
      <webElementGuid>8a2c9637-ea2a-4673-b285-a2545dee0722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/div[@class=&quot;container-fluid page-body-wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 grid-margin stretch-card&quot;]/div[@class=&quot;col-md-12 grid-margin stretch-card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;form-group label-floating is-empty&quot;]/label[@class=&quot;el-switch cbx_status&quot;]/span[@class=&quot;el-switch-style&quot;]</value>
      <webElementGuid>b66a7fbb-539a-4dde-bbeb-9c3fb21864fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>42e537fe-d544-478c-97ed-20e8e30a5b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
