<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Q10</name>
   <tag></tag>
   <elementGuidId>6c467447-acf6-40e2-8c3d-b0a4ab3d9ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Pertanyaan_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Pertanyaan_10&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b3ff1f1-395b-404a-902e-e44f3fe2b260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pertanyaan_10</value>
      <webElementGuid>a2e7b110-13dc-4f7f-8f91-aedff52934ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Comments and Suggestions</value>
      <webElementGuid>cb099c80-9c38-418a-931e-c140a85393e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 row form-group&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/textarea[1]</value>
      <webElementGuid>7949258f-3c2e-42fa-8720-98b3f0d3c6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Pertanyaan_10']</value>
      <webElementGuid>ec4f4e9f-f460-492c-89bf-6b0805ebd8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div[10]/div/textarea</value>
      <webElementGuid>de45b042-5bfe-4fe0-814f-4efff5ae89c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a81a4f6d-ee1a-4b40-b58a-503864534f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Pertanyaan_10' and @placeholder = 'Your Comments and Suggestions']</value>
      <webElementGuid>223b5c34-0668-4b06-97a0-13e2f4f47732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
