<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Q2</name>
   <tag></tag>
   <elementGuidId>8c52b8ec-3d78-49b1-a3e9-39d75695cbee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Pertanyaan_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Pertanyaan_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44a5c4cb-edb2-4b11-aa4b-f661080fad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8af8e7d5-3f2d-4ccd-aa5c-f71cffcf19a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cc39137f-5f40-40f2-afd2-f17b65f8a1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pertanyaan_2</value>
      <webElementGuid>7e1b070f-d428-4623-81b0-337b8a5ec59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Address</value>
      <webElementGuid>70132564-692c-4e3b-9513-f27bcda9e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 row form-group&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>cbee649a-fcf4-4635-8678-9352ceaba779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Pertanyaan_2']</value>
      <webElementGuid>7e86e59f-76e6-4ac9-a1c6-ef3053c392d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div[2]/div/input</value>
      <webElementGuid>aa67bc53-b184-44fa-a18e-414a15b63d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1cc74cf6-becc-45c9-8b37-3a5ff972ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Pertanyaan_2' and @placeholder = 'Your Address']</value>
      <webElementGuid>c00e3d43-02b4-4019-b2d4-741d4cda2b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
