<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Q4</name>
   <tag></tag>
   <elementGuidId>3f077466-ae9b-4d91-8920-5334e0e81848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='inlineCheckbox1'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7d46b56-4870-4dc3-99d7-3bea41789be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8e60716e-59d6-4011-a79b-a097f08ffe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>89bd4559-ae45-4244-b8eb-14391c13ce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineCheckbox1</value>
      <webElementGuid>8b646c53-4d60-428d-969b-c2e2f7121a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Akun Instagram STIKI Malang</value>
      <webElementGuid>b108881c-34ef-4208-841b-1ab472c52b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pertanyaan_4</value>
      <webElementGuid>880ec10c-1385-4e50-b96c-622f68f929ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 row form-group&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/input[@id=&quot;inlineCheckbox1&quot;]</value>
      <webElementGuid>7a76d105-cbc2-4614-970e-fca7911ca998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='inlineCheckbox1'])[3]</value>
      <webElementGuid>75c841f7-0334-4069-952b-c22c86bf497b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div[4]/div/div/input</value>
      <webElementGuid>386602f4-9660-4e3d-9c08-6954a46a4d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>e4797a28-9771-4817-b0bc-b266837e15da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'inlineCheckbox1' and @name = 'Pertanyaan_4']</value>
      <webElementGuid>046c570f-9e11-4528-87e2-3b3949cc7d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
