<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Q9</name>
   <tag></tag>
   <elementGuidId>3833fe9f-c5be-4369-aa09-93208ac1da5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='inlineCheckbox1'])[26]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e08e7b74-ff2d-477d-b17a-e950a085e191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a7c1aae5-b7f7-4f15-9556-f64d43458434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7e340142-90ae-455d-92f3-3361b780ca88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineCheckbox1</value>
      <webElementGuid>01f717b2-83d6-4788-8174-8431c8e8a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>6b2bf6e2-1849-4e5c-896d-bba431d554c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pertanyaan_9</value>
      <webElementGuid>47406402-1e60-43d0-8cf5-4a748bd833b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 row form-group&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/input[@id=&quot;inlineCheckbox1&quot;]</value>
      <webElementGuid>2a054a1c-9cee-4ec4-9de9-64c9fe812f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='inlineCheckbox1'])[26]</value>
      <webElementGuid>37f9f43b-9078-45dc-90a8-5aadcecd0428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div[9]/div/div/input</value>
      <webElementGuid>90c2dc39-19ca-4a5e-aa49-cddfdcb2ff62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>48a4dec9-bebb-4089-a132-604e50dc16e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'inlineCheckbox1' and @name = 'Pertanyaan_9']</value>
      <webElementGuid>e62b8d9b-4c42-4570-9a95-cd2c262f5a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
