<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SuperAdmin</name>
   <tag></tag>
   <elementGuidId>50fb9ad6-67a7-4f67-a624-51396783d627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-black.fw-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to STIKI TECHNOFEST 5.0'])[1]/preceding::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7ae3ed8-0249-4b8b-a4fe-82800b32748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black fw-bold</value>
      <webElementGuid>5fc27f40-6bc4-4bf2-b2a3-3cf52e9a8c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuperAdmin</value>
      <webElementGuid>928952f9-404b-4556-bfc6-3306fb81c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/nav[@class=&quot;navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row&quot;]/div[@class=&quot;navbar-menu-wrapper d-flex align-items-top&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item font-weight-semibold d-none d-lg-block ms-0&quot;]/h1[@class=&quot;welcome-text&quot;]/span[@class=&quot;text-black fw-bold&quot;]</value>
      <webElementGuid>94ebd26e-5fa0-4d21-a9f9-a053314555c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to STIKI TECHNOFEST 5.0'])[1]/preceding::span[1]</value>
      <webElementGuid>67b0b821-aafc-4857-a41a-219d961940b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::span[1]</value>
      <webElementGuid>c875eeda-a91d-4c23-90d7-0945eacb07ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SuperAdmin']/parent::*</value>
      <webElementGuid>e73b0bbf-63a3-42b4-9254-4fcd89fe57cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>81b7cd04-e3a4-4837-8568-dafb534a174a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SuperAdmin' or . = 'SuperAdmin')]</value>
      <webElementGuid>7e6ec156-c39a-46d9-b4e4-ea62281c27ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
