<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User icon</name>
   <tag></tag>
   <elementGuidId>71582d3d-d846-45c2-ad0e-a02b146f1ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-xs.rounded-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UserDropdown']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ec3f452-27a0-404e-9b19-7f6579ba46cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-xs rounded-circle</value>
      <webElementGuid>a28df771-d0ed-490e-b622-f37eb1149824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-icons-png.flaticon.com/512/149/149071.png</value>
      <webElementGuid>d4d67fb4-5577-431b-b85d-c817b18b50a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile image</value>
      <webElementGuid>8ce0e531-c4e0-4c8b-9aac-344808b8060d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/nav[@class=&quot;navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row&quot;]/div[@class=&quot;navbar-menu-wrapper d-flex align-items-top&quot;]/ul[@class=&quot;navbar-nav ms-auto&quot;]/li[@class=&quot;nav-item dropdown d-none d-lg-block user-dropdown&quot;]/a[@id=&quot;UserDropdown&quot;]/img[@class=&quot;img-xs rounded-circle&quot;]</value>
      <webElementGuid>01ea5d99-0405-4d1f-8efb-5934bd0f6154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='UserDropdown']/img</value>
      <webElementGuid>1b86ed0b-5e02-49f0-8f4c-214406a75981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile image']</value>
      <webElementGuid>44870c7e-18b2-4b49-9e04-4f4c96167b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>4a2c8a7e-70bb-49c0-8b85-45a4cd5a9651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-icons-png.flaticon.com/512/149/149071.png' and @alt = 'Profile image']</value>
      <webElementGuid>5cbd9491-78e5-4db0-ad90-b57bf00c0520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
