<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Poster</name>
   <tag></tag>
   <elementGuidId>12776d97-a166-45a8-bdd7-afdbb4229309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgInp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='imgInp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbf0695c-6654-43c6-a05d-de6738123ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>acdf85cf-5c12-4f05-94dc-b0a6439edc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>poster</value>
      <webElementGuid>f3dd07e7-da4e-46f0-931e-6ffbd253e0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>5b8adb37-fa67-406a-afdf-dca93909ad9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgInp</value>
      <webElementGuid>8e124650-e786-49a2-92c6-41e0d3db3246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgInp&quot;)</value>
      <webElementGuid>d9651c46-e0f8-412b-9d1b-caf6e3b8cdff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='imgInp']</value>
      <webElementGuid>12e3f889-65dd-48bd-a037-c71a2d54fe9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>59ad9041-baad-4db4-9206-2eac740f2f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'poster' and @id = 'imgInp']</value>
      <webElementGuid>501d2a50-acce-4172-b7e7-8ffde9924bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
