<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selengkapnya</name>
   <tag></tag>
   <elementGuidId>7ba57467-30ea-4ffe-80b9-7fde1d873884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Selengkapnya')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4bad100-d1c0-467f-abba-8d0498a29ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://technofest.stiki.ac.id/en/project/1021</value>
      <webElementGuid>de15e649-9b45-4898-875f-ce77d6f0bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-more</value>
      <webElementGuid>6c676b9d-a657-4c8b-bef1-d68980764fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selengkapnya</value>
      <webElementGuid>f126dfbe-e33e-4300-ad33-d3948109fbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-wrapper&quot;]/section[@class=&quot;news-section alternate&quot;]/div[@class=&quot;auto-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;news-block col-lg-4 col-md-6 col-sm-12 wow fadeInRight animated&quot;]/div[@class=&quot;inner-box&quot;]/div[@class=&quot;lower-content&quot;]/div[@class=&quot;btn-box&quot;]/a[@class=&quot;read-more&quot;]</value>
      <webElementGuid>091b24ca-e5de-4e48-bd8e-0e5ee364f867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Selengkapnya')])[2]</value>
      <webElementGuid>f1a3f4be-ec54-4b3d-a3d4-4c7055a30af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Smiley Game'])[1]/following::a[1]</value>
      <webElementGuid>d07d4f7d-2c2d-415d-8e58-545ccf88adc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game Application'])[2]/following::a[2]</value>
      <webElementGuid>62308395-a2d1-4087-b04d-e8dc94778b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desain Prototype UI-UX'])[1]/preceding::a[2]</value>
      <webElementGuid>fefbe045-6f0f-454f-877e-99be23f75869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game CX'])[1]/preceding::a[2]</value>
      <webElementGuid>8221f145-1d32-4adc-858f-301890990f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://technofest.stiki.ac.id/en/project/1021')])[3]</value>
      <webElementGuid>b3cd6a23-0bb2-434e-9554-e300eea343b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a</value>
      <webElementGuid>3772b3b7-8c4d-4f8c-84de-48c9bf27792d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://technofest.stiki.ac.id/en/project/1021' and (text() = 'Selengkapnya' or . = 'Selengkapnya')]</value>
      <webElementGuid>1eb29947-ef97-4a7e-8cd4-761600252de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
