<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Desc</name>
   <tag></tag>
   <elementGuidId>cdabb7bb-74a0-41f8-80a5-31599c92ae41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tinymce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>47a8675a-4b0d-462e-903f-358948c8d72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
      <webElementGuid>a36bdf31-b4f5-469d-b3ba-467e6f4efdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mce-content-body </value>
      <webElementGuid>82ffb99d-427f-4f1f-9b84-4ab45aea5da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>mce_0</value>
      <webElementGuid>15caa04f-7648-402d-b8ac-76c774af9d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
      <webElementGuid>c9aa9032-a9ae-4445-86bb-f800a1feb135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b4cfc27-33bf-49c6-9ffb-d89b08f90ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>298a33f8-2a5b-4613-b8ea-011d8822e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test desc</value>
      <webElementGuid>897e2c1c-1e0e-4b91-8be3-6ab4d4ebbe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)</value>
      <webElementGuid>f961ea65-5b98-4971-9b8d-f693cf23a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/z test/test 4/iframe_Paragraph_mce_0_ifr</value>
      <webElementGuid>edfa6c0a-dc2e-4813-a2e1-c55ff0dc109b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body[@id='tinymce']</value>
      <webElementGuid>730aedbc-e39c-4b62-b3c8-46d3eb5db18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>4ec30e35-8564-4351-bae3-625875221fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[@id = 'tinymce' and (text() = 'test desc' or . = 'test desc')]</value>
      <webElementGuid>2ae5b8cf-9f91-4f42-a63b-9f74571dd073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
