<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Speaker photo</name>
   <tag></tag>
   <elementGuidId>f7f7c165-708f-4e65-b4f8-fcff97f0e408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgInp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='imgInp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ea44584-9dfb-4bfc-8dd6-ce69fba7e711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d8e5c530-b78f-48f2-8fa0-b01bc44ec110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>photo</value>
      <webElementGuid>2bc06592-4b8d-4a44-b295-055c5506b41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>386fe4b1-7ac9-4f71-9f7d-f48bd82e8dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgInp</value>
      <webElementGuid>45bec8c7-fe9e-41f3-bd05-c4341d58d045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgInp&quot;)</value>
      <webElementGuid>0ad0fa83-9162-4463-8829-ac23ea4b71c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='imgInp']</value>
      <webElementGuid>09367ff6-891b-4c70-a680-0536b1dcb981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>376f7cd1-da47-4962-b857-bd0ad98ec37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'photo' and @id = 'imgInp']</value>
      <webElementGuid>b6a7f98c-7fb8-44a1-b54c-e3b1d67bfd72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
