<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit button</name>
   <tag></tag>
   <elementGuidId>49083da9-742b-4a91-9921-64f524e98d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_9 > a.btn.btn-sm.btn-success.btn-round > i.mdi.mdi-grease-pencil.menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_9']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8535768c-8da8-45b9-9591-155c6777f610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-grease-pencil menu-icon</value>
      <webElementGuid>20708e4d-0119-4cb7-b3c2-3f180497fa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_9&quot;)/a[@class=&quot;btn btn-sm btn-success btn-round&quot;]/i[@class=&quot;mdi mdi-grease-pencil menu-icon&quot;]</value>
      <webElementGuid>62def641-01a0-4898-802f-3626eef9dbc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_9']/a/i</value>
      <webElementGuid>3be52c1a-5e59-4d2b-b701-17f8fa739d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/form/a/i</value>
      <webElementGuid>b8ed6cc1-3447-4056-b03c-7a95e368df60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
