<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button</name>
   <tag></tag>
   <elementGuidId>fe5ffe74-9516-4911-9fe6-91af88a53814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#27 > i.mdi.mdi-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='27']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cba1af64-e94d-4035-9609-222e925f632c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>5f41d46e-e213-4f98-ac1b-faccdf2fe3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;27&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>39b8a2ef-30d4-4da0-aab7-14bd74c63181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='27']/i</value>
      <webElementGuid>19f06b6b-c451-4586-8423-ee1e75794e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[7]/form/button/i</value>
      <webElementGuid>2af6db1f-a36a-41fe-9f12-83135a6788bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
