<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button major</name>
   <tag></tag>
   <elementGuidId>a6be2f6d-2ca6-426f-a29d-a7098363ce7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9 > i.mdi.mdi-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='9']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c5ace8db-5fe7-49cd-a037-49d7dff227c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>bcb91c56-6a43-4a48-a69e-f232535f3656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>8bb4f9fa-5f18-4934-9889-bd6c061bf7f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='9']/i</value>
      <webElementGuid>9975c3bd-8709-460d-ae10-b3bd4370400d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/form/button/i</value>
      <webElementGuid>077a36cd-c9e4-4bbb-bcb1-f10b1ba18bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
