<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit button</name>
   <tag></tag>
   <elementGuidId>06a30ee5-87f1-40ff-a1f3-93a1115a5708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_26 > a.btn.btn-sm.btn-success.btn-round > i.mdi.mdi-pencil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_26']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e28aaba-0c58-463c-8c5a-1a70acc1076a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-pencil</value>
      <webElementGuid>0ba05100-899e-429a-aa01-3e23b213a808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_26&quot;)/a[@class=&quot;btn btn-sm btn-success btn-round&quot;]/i[@class=&quot;mdi mdi-pencil&quot;]</value>
      <webElementGuid>3ff78283-4010-4f5b-b4c5-257315c42bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_26']/a/i</value>
      <webElementGuid>f3a071c2-11eb-4d0e-8167-e628cf7e5903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[7]/form/a/i</value>
      <webElementGuid>1cbd28ba-115c-4f12-a3bc-3775863c86b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
