<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon user</name>
   <tag></tag>
   <elementGuidId>f96a5fb2-24dc-457b-afdb-4d1b5c251b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UserDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d58eaa38-3f87-48de-9ae9-c856aa4add30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>8edbe39d-e9b5-44e0-9d09-9d8e5b54b04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserDropdown</value>
      <webElementGuid>74d3779a-78f9-4f42-adc9-f8b6b11b6e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>061156a2-da88-470c-a683-4ee2b2b8298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>dfdfa91a-248f-43c9-b59d-3cd8a953dfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9cbd9c4-263b-41fa-ab88-67164054b3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/nav[@class=&quot;navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row&quot;]/div[@class=&quot;navbar-menu-wrapper d-flex align-items-top&quot;]/ul[@class=&quot;navbar-nav ms-auto&quot;]/li[@class=&quot;nav-item dropdown d-none d-lg-block user-dropdown&quot;]/a[@id=&quot;UserDropdown&quot;]</value>
      <webElementGuid>e7c8b468-005e-4d19-98b0-4fd429491794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UserDropdown']</value>
      <webElementGuid>c0873c21-f178-4cd5-8c76-44d215be2575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to STIKI TECHNOFEST 5.0'])[1]/following::a[1]</value>
      <webElementGuid>b90d781d-501f-40ee-ab55-8fd26861248f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alif Fadil Syaifullah'])[1]/following::a[1]</value>
      <webElementGuid>fa06a551-8cfb-4d3c-a91f-1046b5abdea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>a3bf86af-9c34-4bb1-a02d-e8aee19870d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>4876bfee-353a-457f-bcfd-74f74210a76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>be65b0fa-84ba-4dd5-b9cd-46734e31e459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UserDropdown' and @href = '#']</value>
      <webElementGuid>0db54fb4-5f00-4951-84ce-810511e04780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
