<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants</name>
   <tag></tag>
   <elementGuidId>4d38da1a-e67c-4bec-8e58-6049493813fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about']/div[2]/div/div/div/div[2]/div/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.counter-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>39dc484d-7d9b-431f-a16e-153ac6e68f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>counter-title</value>
      <webElementGuid>e34a2a93-586a-41a3-a5a5-9c9cef835082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Participants</value>
      <webElementGuid>86ae58a3-a93c-4e34-885f-4a9dba21e90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;auto-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content-column col-lg-6 col-md-12 col-sm-12 order-2&quot;]/div[@class=&quot;inner-column&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;counter-column col-lg-4 col-md-4 col-sm-12 wow fadeInUp animated&quot;]/div[@class=&quot;count-box counted&quot;]/h6[@class=&quot;counter-title&quot;]</value>
      <webElementGuid>cecf870b-b5fa-45a6-a52c-d01e6891cff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about']/div[2]/div/div/div/div[2]/div/div/h6</value>
      <webElementGuid>a66a91fd-0d1a-49fd-b147-0184aa2a7069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::h6[1]</value>
      <webElementGuid>4533448e-753e-45d1-8fc9-75b778b48a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[3]/preceding::h6[1]</value>
      <webElementGuid>59fe0888-d617-45bb-bb90-1036f0506373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agenda'])[3]/preceding::h6[2]</value>
      <webElementGuid>67838b5b-cdd5-46cf-a956-6f0304eff037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>edf24efb-4684-46e9-b6cc-14224b5be2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Participants' or . = 'Participants')]</value>
      <webElementGuid>3a93ad03-c4fc-4454-97de-68d2986a4889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
