<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Project</name>
   <tag></tag>
   <elementGuidId>b0ecf232-f1cb-49f7-a8d5-e38c50a0f1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about']/div[2]/div/div/div/div[2]/div[2]/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>f38f6da2-4371-4194-9f8e-1290d5ea7f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>counter-title</value>
      <webElementGuid>778b8c47-e6a0-4cad-8dd1-46a95b036d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project</value>
      <webElementGuid>390e8a8c-6b57-4bed-8eb1-c7353f5698eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;auto-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content-column col-lg-6 col-md-12 col-sm-12 order-2&quot;]/div[@class=&quot;inner-column&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;counter-column col-lg-4 col-md-4 col-sm-12 wow fadeInUp animated&quot;]/div[@class=&quot;count-box counted&quot;]/h6[@class=&quot;counter-title&quot;]</value>
      <webElementGuid>79db854e-fbe9-4dd9-8248-6f680e45a53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about']/div[2]/div/div/div/div[2]/div[2]/div/h6</value>
      <webElementGuid>b36c2f02-e5f6-47be-8dd5-74ff17c25350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[3]/following::h6[1]</value>
      <webElementGuid>55ea2974-f5e5-46b0-aaf7-2487f240298a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agenda'])[3]/preceding::h6[1]</value>
      <webElementGuid>9525ff07-3510-4590-bcf2-cd098efeff89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Archive'])[1]/preceding::h6[2]</value>
      <webElementGuid>716303f0-a5e8-464e-a78f-83c45c132da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h6</value>
      <webElementGuid>cf0f4484-b37a-43e5-ae08-ca1dfa5a7aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Project' or . = 'Project')]</value>
      <webElementGuid>9cf14d8f-f413-4c0e-aa74-a6967722f935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
