<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Thumbnail</name>
   <tag></tag>
   <elementGuidId>8372bf02-d205-4f44-a78f-abeace51dcea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sel_thumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sel_thumb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c728b4e-084a-4894-9201-9affc33d7d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>99c2a9b6-6d45-4282-980e-99c90619f21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>btn btn-primary btn-round</value>
      <webElementGuid>f448c6a2-eb6e-4db8-be3d-f4646ea3435c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Choose One</value>
      <webElementGuid>abb9f989-57bb-4903-ae26-1669a0a55cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0b12fe7e-de93-412e-ace3-bba611f061c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>75cc3d0a-80e5-48f4-a6e3-fa35ed4790e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sel_thumb</value>
      <webElementGuid>0931de60-6560-4beb-baf9-a78bca50f5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Onelogo.png</value>
      <webElementGuid>bdea3cb7-c984-4240-b7fb-7380537e8410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sel_thumb&quot;)</value>
      <webElementGuid>a8bd4d8a-91fd-4b2a-a938-d448560f2b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sel_thumb']</value>
      <webElementGuid>ada3c443-f33c-4c85-8808-aa5e4ccaa0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have to upload poster first to choose the thumbnail'])[1]/following::select[1]</value>
      <webElementGuid>a9b2a99b-a393-4cda-80c1-8855c8f8716b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>ed3de6da-97dc-46c1-aad3-273ffe9c0493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Source Code'])[1]/preceding::select[1]</value>
      <webElementGuid>9ebe6128-2fea-4429-93c9-6d8b8d93819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Demo'])[1]/preceding::select[1]</value>
      <webElementGuid>4a128565-8c39-4a71-a5fa-628c615700c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>6665fd39-e952-41f4-bd4f-997355bc0c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Choose One' and @name = 'thumbnail' and @id = 'sel_thumb' and (text() = 'Choose Onelogo.png' or . = 'Choose Onelogo.png')]</value>
      <webElementGuid>2436bc69-f30d-49c4-b099-a54bd2a72828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
