<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button</name>
   <tag></tag>
   <elementGuidId>041c15d2-4b3e-4868-af29-2e1f53041b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1013 > i.mdi.mdi-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>Dele</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7cd85f93-07f4-4534-a3f4-bfd8bd95b760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>9a2bd649-56f4-4594-b9c3-60bd80f8612e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1013&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>4a0068a9-497b-4934-88e8-9a0a8f000a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1013']/i</value>
      <webElementGuid>30f782e6-ad81-4408-be01-88a6ea3b438c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/form/button/i</value>
      <webElementGuid>13730790-4509-43ed-9ccb-b024c5cb0716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
