<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Active Project</name>
   <tag></tag>
   <elementGuidId>545afb6c-e4c0-4681-8375-d0860eab5dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.card-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overview']/div/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>13096fbe-6622-41c5-9f19-63eff906fe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>5d3096d6-dc08-44e7-ad38-2c4cea00f5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active Project</value>
      <webElementGuid>d5bdfbad-4e19-4335-a6d0-00bce389ce4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-3&quot;]/div[@class=&quot;card mb-2&quot;]/div[@class=&quot;card-body&quot;]/h4[@class=&quot;card-title&quot;]</value>
      <webElementGuid>24a9d840-07d7-49b5-8569-3ddd34d31e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overview']/div/div/div/div/h4</value>
      <webElementGuid>811e0c91-21b6-4bb9-aab2-10ffc21d59f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backup'])[1]/following::h4[1]</value>
      <webElementGuid>36278b6d-c732-48b7-969a-f619557d98f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quizioner'])[1]/following::h4[1]</value>
      <webElementGuid>dc5ce1fe-36b7-4741-9776-cee403ee693a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Active Project'])[1]/preceding::h4[1]</value>
      <webElementGuid>3a1d2aca-2dda-4ece-8766-37a587eb1712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Speaker'])[1]/preceding::h4[2]</value>
      <webElementGuid>55bc4ba2-3aec-4058-8fa3-9f67e97fca55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active Project']/parent::*</value>
      <webElementGuid>da1c3d67-ebaf-418d-93a4-60f82be533ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/h4</value>
      <webElementGuid>a0c22b16-7724-4242-8ac8-5851c9538fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Active Project' or . = 'Active Project')]</value>
      <webElementGuid>950d00d1-fe66-45aa-b542-a9ad16e5abae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
