<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-Active Project</name>
   <tag></tag>
   <elementGuidId>1ce5d28c-6b47-4e0d-aab3-621d91c71005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overview']/div/div[2]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>3d1aa927-bc84-4094-942b-44407b6627a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>879f3ebd-61ea-4e3c-b33c-cf14e8f26a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non-Active Project</value>
      <webElementGuid>8a7732da-c8a3-44ec-b684-bd31b3092923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-3&quot;]/div[@class=&quot;card mb-2&quot;]/div[@class=&quot;card-body&quot;]/h4[@class=&quot;card-title&quot;]</value>
      <webElementGuid>1b7ffa96-2783-4502-a7d0-180259ff6131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overview']/div/div[2]/div/div/h4</value>
      <webElementGuid>5c9070fd-4131-472a-9a6a-71023a76ab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Project'])[1]/following::h4[1]</value>
      <webElementGuid>cdb7d2eb-e0b2-4950-bec3-8cae240d3725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backup'])[1]/following::h4[2]</value>
      <webElementGuid>c41566bf-feab-48cb-9375-280509febe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Speaker'])[1]/preceding::h4[1]</value>
      <webElementGuid>4ee2de3e-8f79-4d06-9952-5b798cd84a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Agenda'])[1]/preceding::h4[2]</value>
      <webElementGuid>2f4563db-fb75-420b-a98f-86b7cc5125bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Non-Active Project']/parent::*</value>
      <webElementGuid>2d0db87d-3b4a-466e-a374-7e647a48c554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h4</value>
      <webElementGuid>681cfbe4-328c-4e02-82c0-e4af0e20d1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Non-Active Project' or . = 'Non-Active Project')]</value>
      <webElementGuid>05c9d985-b2cc-45e7-84d4-8c530ba83ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
