<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Test major edit fddfdfd</name>
   <tag></tag>
   <elementGuidId>9065c8b2-d7f3-4854-9161-b9a382a2e96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tinymce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>13dca08c-e43e-44b1-ba5b-47f53b3fcd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
      <webElementGuid>115eeda7-2a20-4fe5-a96d-05ac4629041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mce-content-body </value>
      <webElementGuid>7de01228-baf4-4484-88e9-e0b753187e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>mce_0</value>
      <webElementGuid>dada7929-4e10-4f7f-b3c2-c828badb1837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
      <webElementGuid>30c7f981-662e-4f26-b497-239241ba0e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e086f51-56e9-462a-bdb1-b7bd6d8e8373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>323910a1-0381-4f5b-86ed-d4db77a0c3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test major edit fddfdfd</value>
      <webElementGuid>71cdbc62-9791-475a-9f37-98c65f686c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)</value>
      <webElementGuid>2196422a-015b-43be-bb98-434ca02740ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/z test/test 2/iframe_Paragraph_mce_0_ifr</value>
      <webElementGuid>e85e01a7-37e3-433d-b16f-c4bdd326cc0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body[@id='tinymce']</value>
      <webElementGuid>2187bf74-0df9-49b1-8199-218328a57500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>621f6162-84ae-4ff2-8ad3-d7cf922e1d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[@id = 'tinymce' and (text() = 'Test major edit fddfdfd' or . = 'Test major edit fddfdfd')]</value>
      <webElementGuid>98c98423-1302-482a-bdcb-5f44a50f3588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
