<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Test major edit_mdi mdi-grease-pencil menu-icon</name>
   <tag></tag>
   <elementGuidId>7c29465c-ab37-4db3-aea7-d240e56d882c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_6 > a.btn.btn-sm.btn-success.btn-round > i.mdi.mdi-grease-pencil.menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_6']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>92cfc81a-82c0-4a5f-af9e-3dc565c6d3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-grease-pencil menu-icon</value>
      <webElementGuid>cff08c2b-04f4-4662-84da-6a206363c3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_6&quot;)/a[@class=&quot;btn btn-sm btn-success btn-round&quot;]/i[@class=&quot;mdi mdi-grease-pencil menu-icon&quot;]</value>
      <webElementGuid>00bcecbe-9157-45da-9a89-5b7d37ee2079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_6']/a/i</value>
      <webElementGuid>042a2292-563d-4a25-a6db-060c4d16d5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/form/a/i</value>
      <webElementGuid>eb85d054-cbae-461c-9002-11fb85bb6477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
