<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>d17f5e01-a8e8-472c-bcef-1e1531bfeb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.theme-btn.btn-style-two > span.btn-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form']/form/div[4]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9040fe1-3fef-445a-8e4f-3e25645520c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-title</value>
      <webElementGuid>18cc1613-f91f-4bb5-8843-1ece16ffc42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d9539093-814d-4b43-90b0-f70090e4561e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/form[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;form-group pull-left&quot;]/button[@class=&quot;theme-btn btn-style-two&quot;]/span[@class=&quot;btn-title&quot;]</value>
      <webElementGuid>0597fca4-4d15-4f73-bcad-56ce91f0c809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/form/div[4]/div/button/span</value>
      <webElementGuid>f61cf71c-52e9-4cb2-8ebe-25ebc5272ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password ?'])[1]/following::span[1]</value>
      <webElementGuid>38a7f677-c2ac-4610-b48e-1445fa1520f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[5]/following::span[5]</value>
      <webElementGuid>66b75612-2eea-451b-8849-9be9c61eb8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HERE'])[1]/preceding::span[1]</value>
      <webElementGuid>548b0759-25d6-4407-b3ed-46a40a9dfb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/span</value>
      <webElementGuid>a8eee239-ca9c-4210-aaaf-a5b1aa8b5484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d42828c6-2df1-497d-a0f6-cca8ad7051d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
