<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Superadmin</name>
   <tag></tag>
   <elementGuidId>9a40ab86-5083-41bd-be64-1f8104eeb5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.active > a.nav-link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-elements']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dd43ef9-78fb-477e-ba1a-099596f0f204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>8d8c1e36-f183-4888-a97b-19fb7a2cbc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://technofest.stiki.ac.id/en/backsite/user/?role=1</value>
      <webElementGuid>38fb355a-10c9-4171-af6e-87e5119d76bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Superadmin</value>
      <webElementGuid>50c2e968-498b-4401-b73e-9e1ae4ca78e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-elements&quot;)/ul[@class=&quot;nav flex-column sub-menu&quot;]/li[@class=&quot;nav-item active&quot;]/a[@class=&quot;nav-link active&quot;]</value>
      <webElementGuid>fad5638e-d402-4d73-95fd-4f41afc757e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-elements']/ul/li/a</value>
      <webElementGuid>29f4f8a5-7bf8-428e-be44-ecc19d32ed5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Superadmin')]</value>
      <webElementGuid>26bbf2ed-8ae7-4a7f-b1e8-833daaa1cda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::a[1]</value>
      <webElementGuid>ef3076ea-52c0-40e2-9ea8-a42efd210a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lecturer'])[1]/following::a[2]</value>
      <webElementGuid>167f6f18-747e-4e4f-9a7b-11b1a72c3f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moderator'])[1]/preceding::a[1]</value>
      <webElementGuid>ae441698-45a2-401d-9823-3ae3115ef72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participant'])[1]/preceding::a[2]</value>
      <webElementGuid>b420ee32-3f6a-4a20-8cc8-7f8d50a501cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Superadmin']/parent::*</value>
      <webElementGuid>0ba654c1-dbba-4bda-a33c-49f182d5cf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://technofest.stiki.ac.id/en/backsite/user/?role=1')]</value>
      <webElementGuid>452c7fe7-f53e-42c9-8101-2c353092a4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li/a</value>
      <webElementGuid>eb3aca9d-8320-4f48-9d32-5ed219e8f24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://technofest.stiki.ac.id/en/backsite/user/?role=1' and (text() = 'Superadmin' or . = 'Superadmin')]</value>
      <webElementGuid>e4e79ed3-4dea-4125-899f-aa844c1fe2ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
