<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button superadmin</name>
   <tag></tag>
   <elementGuidId>d0c2d52a-4ab8-4260-8cd6-2b05c2d2a04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1023 > i.mdi.mdi-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1023']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2cc51c63-3e89-4aff-a7b8-c2dd0b8b4111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>48a00a02-4d56-4ecb-ad94-04297d05d6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1023&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>e73bbc3c-01f2-4549-8017-f2ffa0550749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1023']/i</value>
      <webElementGuid>1fa84f3d-506e-4d0b-9344-f9ff8a4fea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/form/button/i</value>
      <webElementGuid>9cb374fc-acc1-4e53-8fd1-7afe7309f220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
