<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete 1</name>
   <tag></tag>
   <elementGuidId>27076d21-d93d-4115-80db-04b2fc3899e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='9']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1c849262-c875-4938-abe7-65c65ef58250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>d8962d3b-ccc6-4aae-8d6d-fc8e7761983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>87af63d6-974d-45fb-95f2-26a4f3ea97c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='9']/i</value>
      <webElementGuid>97a544f8-5b90-49fb-9e0d-f5ca249c34bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[6]/form/button/i</value>
      <webElementGuid>780f518a-95a0-4b6b-9cc2-a6ece250758d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
