<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button semester</name>
   <tag></tag>
   <elementGuidId>6587ea93-24d5-4e3d-970e-18ef20ba0bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#11 > i.mdi.mdi-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='11']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b76e84cd-1050-41cb-b8b5-530b508316c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>dc98d589-e976-4b78-82e1-0aedc2cbb9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>0d101e97-d7b2-45d1-a147-d884ebd1852f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='11']/i</value>
      <webElementGuid>a296ea77-80f3-4f52-91e6-e9eb9392b9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[6]/form/button/i</value>
      <webElementGuid>c06b9c25-6e45-470c-b545-2b95796bafd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
