<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit button</name>
   <tag></tag>
   <elementGuidId>4a5f827c-9fcb-4f19-bc40-6ad4c5ed75c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-grease-pencil.menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_6']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3db0c6f2-b948-4cde-bdc9-05d92c5e34dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-grease-pencil menu-icon</value>
      <webElementGuid>75fc4e86-0fdf-4e88-b948-23d61354e7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_6&quot;)/a[@class=&quot;btn btn-sm btn-success btn-round&quot;]/i[@class=&quot;mdi mdi-grease-pencil menu-icon&quot;]</value>
      <webElementGuid>1f162049-407a-4ba1-8847-0378dd218d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_6']/a/i</value>
      <webElementGuid>155f9ebe-61ff-4f61-854c-b60b5259002a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a/i</value>
      <webElementGuid>20b98c69-4bb5-46bd-be28-f806a5d56153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
