<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>44203712-8d5f-4008-9620-9c821c818ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.theme-btn.btn-style-two > span.btn-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form']/form/div[4]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08e88ded-dbc1-4b19-a158-b37e1a0991b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-title</value>
      <webElementGuid>000c3b4b-8ef5-48dc-9e6f-a11c6c610eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>703a9204-7af3-4faf-afba-8eff89029b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/form[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;form-group pull-left&quot;]/button[@class=&quot;theme-btn btn-style-two&quot;]/span[@class=&quot;btn-title&quot;]</value>
      <webElementGuid>ec8f4c2b-5cd8-4974-a906-79e7af119fb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/form/div[4]/div/button/span</value>
      <webElementGuid>b40a7098-8640-488a-84bb-a9700a0b4ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password ?'])[1]/following::span[1]</value>
      <webElementGuid>e1984abb-26f1-45e1-8556-2dd68ff169a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[5]/following::span[5]</value>
      <webElementGuid>a8d932a2-2e04-487c-8350-94f503a843f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HERE'])[1]/preceding::span[1]</value>
      <webElementGuid>eb59fde4-a3d2-4200-a2b1-8498b310fabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/span</value>
      <webElementGuid>8b67df35-4fc2-411b-81cb-fd2f88a3d287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>8d3cb3dd-f94f-4925-968c-1e811dbef1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
