<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detail button</name>
   <tag></tag>
   <elementGuidId>b6be333c-b4bb-4144-9a02-b0273ea80045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_872']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b497e91d-0d06-4fd5-977c-9f35def5f9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-eye</value>
      <webElementGuid>ed42beb6-5f9b-411e-ab79-fa4f058a9ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_872&quot;)/a[@class=&quot;btn btn-sm btn-info btn-round&quot;]/i[@class=&quot;mdi mdi-eye&quot;]</value>
      <webElementGuid>a866c5d7-0438-41f2-88b4-bcb32661d646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_872']/a/i</value>
      <webElementGuid>9b6140ee-756d-4891-8155-1f6859cba255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a/i</value>
      <webElementGuid>4f067986-b4ce-4726-aeb8-24b332a0158c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
