<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button moderator</name>
   <tag></tag>
   <elementGuidId>e0aeb1a2-9172-4c11-8f10-120978ed4967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1030']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1030 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>96aa4821-e21e-4398-a5df-a87370bdf33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>47752ac6-2548-4d1c-9a08-d13572e370ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1030&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>18e02af3-162a-41f8-9381-bfe81da427be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1030']/i</value>
      <webElementGuid>e9bdffdf-f67e-4b52-802f-1dce3ec6e7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/form/button/i</value>
      <webElementGuid>7161d90e-bf0e-4bc3-9439-4722175817c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
