<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button quizioner</name>
   <tag></tag>
   <elementGuidId>bc9b9b4e-0ed4-407e-ac5e-c4d212e0115a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='31']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#31 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6131cc97-3ac8-4abf-8f30-01766d1b3c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>9af0d566-782d-4073-93ec-d6a100c2bc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;31&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>0ba8d0d7-d02f-4e6d-ba04-2bdd689135e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='31']/i</value>
      <webElementGuid>bba8d98c-826c-4081-87f2-a0fbf86d507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[7]/form/button/i</value>
      <webElementGuid>de84ba1b-6566-44b4-b7bf-2aae679b88a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
