<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button dosen</name>
   <tag></tag>
   <elementGuidId>54e42563-0697-4102-b5ed-a92a92252a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='42']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>368a4655-d27a-46a1-991e-b6c0e9730926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>fbb5fe49-1153-4ffd-9651-3e6635bbab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;42&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>7afb29ae-7aee-492e-a308-88fc0e7424e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='42']/i</value>
      <webElementGuid>a85c46b9-d4d7-46f9-a4b5-4a16528b2118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>c4dff1cb-32f5-4e78-a597-798a7008cf9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
