<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button major</name>
   <tag></tag>
   <elementGuidId>bded3953-2bbb-4c92-82c7-852a348259a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='10']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#10 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2b3390f5-cac2-408e-a4cf-2b29598d662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>e85bff2b-fc57-47be-9926-8e1e2434b970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>94475dec-e593-4a52-a353-025ac2853f6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='10']/i</value>
      <webElementGuid>bf2df253-9290-445e-a9d6-28be504ed82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/form/button/i</value>
      <webElementGuid>6d6e66df-b570-4276-b39d-ef20ce098660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
