<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button superadmin</name>
   <tag></tag>
   <elementGuidId>1ddc0a77-ba91-48e5-9615-77d929c6fe88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1029']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1a3358c0-15e4-453e-ac60-65b9a10ae2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>dcd7ac1f-8500-4df5-9cff-94d5b3bb604a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1029&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>99ddb967-38d2-49ce-b2b6-90ddec49f800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1029']/i</value>
      <webElementGuid>31ec0a68-8f12-4340-8351-5cf31d297edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>d712e69f-3d84-4de2-9828-58225582b627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
