<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button semester</name>
   <tag></tag>
   <elementGuidId>47e53bb5-64d9-4d07-9450-f2b477844487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='12']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#12 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1cd96043-5f1e-4e1e-840c-313ecd52d745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>8ebd58f9-cc41-4ca9-a8c6-44b02ec3a562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;12&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>40a7b1df-8eef-44c4-a780-a23453b56bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='12']/i</value>
      <webElementGuid>f58cfecf-3ec1-409e-841b-f84b33934acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/form/button/i</value>
      <webElementGuid>b4e343c7-b88b-4bfe-9f29-7ef5a7ff918f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
