<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button event</name>
   <tag></tag>
   <elementGuidId>e9c51cef-7911-4b68-97d8-c48ad665df6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='25']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#25 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ca0cc4ec-677f-44b3-a062-143c2ae0522a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>48b23228-d34d-4902-ba0b-4a32884f6e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;25&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>de6eebb0-88b2-41c7-a136-ccee4b230e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='25']/i</value>
      <webElementGuid>d568de6f-3654-4aaa-8b54-6ee59248009f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/form/button/i</value>
      <webElementGuid>8ef10cea-6ceb-4c9b-b465-8cbb34977770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
