<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button participant</name>
   <tag></tag>
   <elementGuidId>e6b7b2f8-358e-4291-9c18-c999b309ea15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1031']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6cc78ca9-01d5-4ea5-9589-294fb8f9311f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>65b68347-3761-4c0d-8651-b713ed1db056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1031&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>2014cc51-23d9-44c9-96c5-b5cd76b49f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1031']/i</value>
      <webElementGuid>e5890a4f-aca2-414e-93f0-44b632ddeae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>9c8f63d1-dd47-4b6b-8b04-53d4a95bd54e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
