<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button moderator</name>
   <tag></tag>
   <elementGuidId>a337bcdb-be1b-4466-a33e-50da238d25f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1033']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1033 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>16c08d10-7e43-4314-aefd-4e94b1473910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>b497d48f-33d8-4dda-b843-3106aeef4231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1033&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>8f37514a-3da6-49ad-9122-0490fad5cacc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1033']/i</value>
      <webElementGuid>768f4fa8-8565-4521-a172-72d77f99e0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/form/button/i</value>
      <webElementGuid>d13b1e4b-9358-46e6-b263-9e07aab8c0ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
