<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete button semester</name>
   <tag></tag>
   <elementGuidId>8518f844-afb6-4764-82d8-2a980901520d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='13']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#13 > i.mdi.mdi-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b7c724ad-f79a-41f4-b2d0-6fea6f69ccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>efaa67fb-2ce7-427c-9d4d-1269f6a98fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13&quot;)/i[@class=&quot;mdi mdi-delete&quot;]</value>
      <webElementGuid>81d1bec0-51bf-473d-9383-fea90029a71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='13']/i</value>
      <webElementGuid>34b6fc77-f091-4f82-844c-22dec8ad6e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/form/button/i</value>
      <webElementGuid>0ae93da1-6f37-42b7-884f-a296867185cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
