<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>About EN</name>
   <tag></tag>
   <elementGuidId>79b8435d-4ddf-4d96-b655-ee95a7021bd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mce_2_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mce_2_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3dc520e3-7dfa-482e-a330-09c1c1d023fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce_2_ifr</value>
      <webElementGuid>285981d7-1500-41fe-81ea-4ba058786204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0d59afda-4fcf-4930-8bc4-d295642de4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e1c36e4-6b5d-4971-b53b-aebcce59f135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>f8d16c55-99ee-43da-b850-6539a99f3e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>f6126dca-8dcd-4827-8e18-7385e40517a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce_2_ifr&quot;)</value>
      <webElementGuid>e1fd50b4-252f-4205-9a8e-62d784acaa22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mce_2_ifr']</value>
      <webElementGuid>ed950819-6087-4afb-a959-d4a4c0ddb6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/iframe</value>
      <webElementGuid>932bc9ad-d988-47a1-b0f3-dc951240555c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mce_2_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>cd785472-6425-4c7e-95b6-28c0c7773add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
