<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>About</name>
   <tag></tag>
   <elementGuidId>22f79259-bb85-4800-9794-9fd9f13dca6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mce_0_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mce_0_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>66c0edfb-2109-46a5-afd0-b5627a79330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce_0_ifr</value>
      <webElementGuid>162747b4-2382-4eb8-882a-59b82ce66604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8f5e8a7-e1b1-4162-8aff-b294b38d73e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5097b21b-94a9-4a05-a796-922074c36132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>86fb6de0-f0b2-479f-b6c2-173db4653b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>a9992179-7c08-4131-8b09-d2912946fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce_0_ifr&quot;)</value>
      <webElementGuid>68679080-ffe5-4bc6-98a8-d35b3792e9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mce_0_ifr']</value>
      <webElementGuid>d18f866d-2ac7-41f4-b6a8-60370f4c3191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ba6b4c8b-8519-4685-81fb-1c3525be6ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mce_0_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>bbf8340e-e7f9-43ff-b0f6-751ae2c7d015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
