<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alif Fadil Syaifullah</name>
   <tag></tag>
   <elementGuidId>2410e347-378a-412a-b732-4ed41298a7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2b140d5-5897-4ecc-b537-56a8c78a3a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://technofest.stiki.ac.id/user/191131007%40mhs.stiki.ac.id</value>
      <webElementGuid>1ec0b775-de8b-4915-b060-776e20376b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alif Fadil Syaifullah</value>
      <webElementGuid>23ac2937-2d35-416c-990c-c85d28af4ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[1]</value>
      <webElementGuid>5b7c5e96-a2ff-4c2d-9fc2-1be9b7f1811a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[3]/a</value>
      <webElementGuid>ca69ae34-b513-42c7-94ce-cc1c1dbe99d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alif Fadil Syaifullah')]</value>
      <webElementGuid>f705f9a6-b563-4336-8941-327e6916392b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Peserta'])[1]/following::a[1]</value>
      <webElementGuid>ed073a0a-a1db-422f-b75e-ce2e34962ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRP'])[1]/following::a[1]</value>
      <webElementGuid>d7017287-9f36-4108-9fd8-62a2cd14a6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alif'])[1]/preceding::a[1]</value>
      <webElementGuid>31a68ee0-ea3f-461a-b2bc-449ab10445b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 2 of 2 entries (filtered from 530 total entries)'])[1]/preceding::a[2]</value>
      <webElementGuid>0db1dbbe-c3b4-4f5a-a6ac-b2996c31280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alif Fadil Syaifullah']/parent::*</value>
      <webElementGuid>7c202976-fdc3-4fd5-bb50-f3567e4ca679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://technofest.stiki.ac.id/user/191131007%40mhs.stiki.ac.id')]</value>
      <webElementGuid>ffeb4153-9abf-4b49-960a-9b09a74bfc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>db91b75f-168d-44ba-bb10-7fda3518368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://technofest.stiki.ac.id/user/191131007%40mhs.stiki.ac.id' and (text() = 'Alif Fadil Syaifullah' or . = 'Alif Fadil Syaifullah')]</value>
      <webElementGuid>5f475de5-f209-4162-a0ca-0e82591c10b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
